name: ChoCallate
channels:
  - conda-forge
  - bioconda
dependencies:
  - freebayes=1.3.9
  - samtools=1.21
  - python=3.13.2
  - tabix=1.11
  - bowtie2=2.5.4
  - bedops=2.4.42
  - gatk4=4.6.1.0
  - snver=0.5.3
  - vardict-java=1.8.3
  - nextflow=24.10.6
