name: ChoCallate
channels:
  - conda-forge
  - bioconda
dependencies:
  - freebayes
  - samtools
  - python
  - tabix
  - bowtie2
  - bedops
  - gatk4
  - snver
  - vardict-java
  - nextflow
  - bcftools
  - bedtools
  - parallel
  - pysam
  - bwa
  - minimap2
