name: ChoCallate
channels:
  - conda-forge
  - bioconda
dependencies:
  - bwa
  - minimap2
  - bowtie2
  - freebayes
  - bcftools
  - gatk4
  - vardict-java
  - varscan
  - samtools
  - python
  - tabix
  - bedops
  - nextflow
  - bedtools
  - parallel
  - pysam
  - picard
