input:
  samples_tsv: "/home/projects/dev/ChoCallate/test_data/samples.tsv"
  reference_genome: "/home/projects/dev/ChoCallate/test_data/arth_chr1.fasta.gz"
  reference_index_dir: "/home/projects/dev/ChoCallate/test_data/"
  custom_bed: null
  format: "fastq"
  reads_type: "pe"

output:
  directory: "/home/projects/dev/ChoCallate/test_data/ChoCallate_output"
  type: "single"
  format: "bcf"

ref_genome:
  bgzip: true

mapping:
  mapper: "bowtie2"
  cpu: 10

bam_filter:
  min_map_qual: 0

rmdup:
  enabled: false

left_align_indels:
  enabled: true

coverage:
  min_coverage: 2

calling:
  callers: "bcftools,gatk,freebayes"
  min_snp_qual: 20
  cpu: 7
  bcftools:
    call:
      extra_args: ""
    mpileup:
      extra_args: ""
  freebayes:
    extra_args: ""
  gatk:
    extra_args: ""

consensus:
  threshold: 2
  cpu: 4
