samples_tsv: "/home/projects/dev/ChoCallate/test_data/samples.tsv"
outdir: test_data/chocallate_test_2
reference_genome: "/home/projects/dev/ChoCallate/test_data/arth_chr1.fasta.gz"
cons_threshold: 3
custom_bed: null
input_format: "fastq"
reads_type: "pe"
ploidy: 2
callers: "bcftools,gatk,freebayes,snver,vardict"

reference_preparation:
  decompress:
    bgzip: true
    cpu: 1
  fai_index:
    cpu: 1

bam_preparation:
  mapping:
    mapper: "bowtie2"
    forks: 1
    bowtie2:
      cpu: 10
      extra_args: "--no-unal"
    bwa:
      cpu: 10
      extra_args: ""
    minimap2:
      cpu: 10
      extra_args: ""
  filter:
    cpu: 1
    forks: 1
    min_map_qual: 0
    samtools:
      view:
        extra_args: "-F 4"
  rm_duplicates:
    enabled: false
    cpu: 1
    forks: 1
    extra_args: "--VALIDATION_STRINGENCY SILENT --REMOVE_DUPLICATES true"
  left_align_indels:
    enabled: true
    cpu: 1
    forks: 1
    extra_args: ""

coverage:
  cpu: 1
  forks: 1
  min_coverage: 1
  extra_args:
    depth: "-J"

calling:
  min_base_quality: 0
  min_snp_qual: 0
  bcftools:
    cpu: 5
    forks: 1
    extra_args:
      call: "--multiallelic-caller --variants-only"
      mpileup: "--count-orphans --max-depth 250"
  freebayes:
    cpu: 5
    forks: 1
    extra_args: "--use-best-n-alleles 4 --hwe-priors-off --no-population-priors --allele-balance-priors-off --haplotype-length -1 --throw-away-complex-obs --no-partial-observations --limit-coverage 250"
  gatk:
    cpu: 5
    forks: 1
    extra_args: "--do-not-run-physical-phasing true --smith-waterman FASTEST_AVAILABLE --create-output-variant-index false --native-pair-hmm-threads 1"
  vardict:
    cpu: 5
    forks: 1
    extra_args: "--nosv -k 0"
  snver:
    cpu: 5
    forks: 1
    extra_args: "-p 0.01"

consensus:
  cpu: 32
  forks: 1

output:
  type: "sample" # single - single file (all samples, all variant types), sample - separate file for each sample (all variant types) 
  format: "bcf" # output compressed VCF (vcf) or compressed BCF (bcf)