input:
  samples_tsv: null
  reference_genome: null
  reference_index_dir: null
  custom_bed: null
  format: "fastq"
  reads_type: "pe"

output:
  directory: "ChoCallate_output"
  type: "sample"
  format: "bcf"

ref_genome:
  bgzip: true

mapping:
  mapper: "bowtie2"
  extra_args: ""
  cpu: 10

bam_filter:
  min_map_qual: 10

rmdup:
  enabled: false

left_align_indels:
  enabled: true

coverage:
  min_coverage: 3

calling:
  callers: "bcftools,gatk,freebayes"
  min_snp_qual: 20
  cpu: 4
  bcftools:
    call:
      extra_args: ""
    mpileup:
      extra_args: ""
  freebayes:
    extra_args: ""
  gatk:
    extra_args: ""

consensus:
  threshold: null
  cpu: 4
