ploidy: 2

input:
  samples_tsv: null
  reference_genome: null
  custom_bed: null
  format: "fastq"
  reads_type: "pe"

output:
  directory: "ChoCallate_output"
  type: "sample"
  format: "bcf"

ref_genome:
  bgzip: true

mapping:
  mapper: "bowtie2"
  cpu: 10

bam_filter:
  min_map_qual: 0

rmdup:
  enabled: false

left_align_indels:
  enabled: true

coverage:
  min_coverage: 1

calling:
  callers: "bcftools,gatk,freebayes,snver,vardict"
  min_base_quality: 0
  min_snp_qual: 0
  cpu: 4
  bcftools:
    call:
      extra_args: "--multiallelic-caller --variants-only"
    mpileup:
      extra_args: "--count-orphans --max-depth 250"
  freebayes:
    extra_args: "--use-best-n-alleles 4 --hwe-priors-off --no-population-priors --allele-balance-priors-off --haplotype-length -1 --throw-away-complex-obs --no-partial-observations --limit-coverage 250"
  gatk:
    extra_args: "--do-not-run-physical-phasing true --smith-waterman FASTEST_AVAILABLE --create-output-variant-index false --native-pair-hmm-threads 1"
  vardict:
    extra_args: "--nosv"
  snver:
    extra_args: "-p 0.01"

consensus:
  threshold: null
  cpu: 4
